#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
sudo apt-get  update -y
sudo apt-get install nginx -y

# allows nginx on firewall
ufw allow 'Nginx HTTP'

# Creating new index
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Starts nginx
sudo service nginx start
