#!/usr/bin/env bash
# Install the load balancer
sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get install haproxy=2.6.\*

echo "
frontend  londysiba-frontend
        bind *:80
        mode http
        default_backend londysiba-backend
backend londysiba-backend
        balance roundrobin
        server web-01 54.144.222.14:80 check
        server web-02 3.85.41.204:80 check" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | tee -a /etc/default/haproxy

service haproxy restart