#!/usr/bin/env bash
# Nginx likes port 80
# Debbuging skills on what's keeping mu=y Ubuntu container's
# Nginx installation from listening on port 80.

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
