#!/usr/bin/env bash
# Display the list of currently running processes.

echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"

ps axo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest | head -n 51 | tail -n +2
