#!/usr/bin/env bash
# Display the list of currently running processes.

echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"

ps axo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest | awk '{printf "%-10s %-5s %-4s %-4s %-6s %-5s %-8s %-4s %-8s %-7s %s\n", $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $NF}'
