#!/usr/bin/env bash
#  a Bash script that displays the PID, along with the process name, of processes whose name contain the word bash.

script_pid=$$

for pid_dir in /proc/*/; do
	current_pid=$(basename "$pid_dir")
	cmdline=$(tr -d '\0' < "$pid_dir/cmdline" 2>/dev/null)
	if [[ "$current_pid" -ne "$script_pid" && "$cmdline" =~ bash ]]; then
		process_name=$(tr -d '\0' < "$pid_dir/comm" 2>/dev/null)
		echo "$current_pid $process_name"
	fi
done
