#!/usr/bin/env bash
# a Bash script that stops 4-to_infinity_and_beyond process

./4-to_infinity_and_beyond.sh &

bg_process_pid=$!

read -p "Press enter to stop this script. The other process will keep running."

kill -SIGTERM $bg_process_pid

echo "Terminated"
